AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:nNN/AB9XIQRut4Sv+kRfebYzSS8=,iv:KNkPaTy/A4prx7rpHLdiWDeM9fgAGQP5NiNtX637IP4=,tag:FcLLYYfdWylm6nM24O6sAA==,type:str]
AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Irh5UXGPDgonXGs3RdaBIBOl1oo/eRWX/WVaNC6pgmOzrzxdFHpxTQ==,iv:opbtA7Sab25lHvVp6wiC64mowhanMVihxWACA0RajDU=,tag:Y24csAawA7NHIsj2IZ23UA==,type:str]
TF_VAR_state_encryption_passphrase: ENC[AES256_GCM,data:pbDTboqmIPv4vUBQEYoN354eT2pOjEuL82a6pFeiMXM=,iv:UXbJIrAj8mthmm/FYBlKt4jTGi0zsc7cHIg9oPOXvS4=,tag:AEQSToR0/B+5k++4ov6+cQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QjJWT21XTHJ3Y3Joc0F6
            cytSWkVydzRVYTZoNXQxZzdJL0tMSTdwOVRvClVpZ1ZPcjhMOWlON2pPOG1oc2hB
            dWxuMjA2ajJLdnZ2dnBFOElITXBsQmsKLS0tIGtoT0tPUTZOZDFtQUlEdXdkN1po
            Wm4vVUhWWlJXT2llZzNJdlVxNWJoOHMKcubhuyDtkqBwiHwUINCMLn98F0gyVwCB
            yRDMGV4YaMX3Jl2t/Y//Ia4G1r5latHKCNOwAI9/M/+I9pPV+s2MEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gtvmhupwwu4gmld3jzheewjt4wjt63sfv9cxkx2angsdudngkf3qw2pltu
    lastmodified: "2026-08-23T10:24:47Z"
    mac: ENC[AES256_GCM,data:AGZQtVYGoNSs1PIAeBvDLOKfwKhOovtytFZAAO5tD8rkEtwbXs0x8dRNzzoH7quZfquIQMCrnSe6iRrhNH4HbIODRb/aRpaMhiiVWARqYv5w3v5NgiG8+BKxb3LyBI4qbVvir7OCbnn0HbcPnKYfYwI62sH0F87xGn6tslAQw88=,iv:4098OGQYMowr1UnalbFOoawR9w1B9ggB2kQPszK846g=,tag:AfGZtC7aFh82p+b3iZUAyA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
